/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.empleadofuncional.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.empleadofuncional.modelo.BeansCaso;
import sv.edu.udb.empleadofuncional.modelo.ModeloCaso;
import sv.edu.udb.util.Sesion;

/**
 *
 * @author Ricardo
 */
public class MostrarCasos extends javax.swing.JInternalFrame {
    static int bandera=0;
   
    private Sesion sesion;    
    /**
    
     * Creates new form MostrarCasos
     * @param sesion
     */
    DefaultTableModel modelo1=null;
    public MostrarCasos(Sesion sesion) {
        this.sesion=sesion;
        initComponents();
        llenarTabla();
        Object [][] data=null;
        String[] columns={
            "Codigo","Descripcion","Fecha Liminte","Programador asignado","Estado de la solicitud"
        };
        modelo1=new DefaultTableModel(data,columns);
        this.jTable1.setModel(modelo1);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                cerrar(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void llenarTabla(){
        ModeloCaso mCaso=new ModeloCaso();
        ArrayList<BeansCaso> arreglo=mCaso.mostrarCaso(sesion.getId());
        modelo1.setNumRows(0);
        for(BeansCaso user:arreglo){
             Object[] newRow={user.getCodigoCaso(),user.getDescripcionCaso(),user.getFechaLimite(),user.getProgramadorAsignado(),user.getEstadoSolicitud()};
             modelo1.addRow(newRow);
        }
    }
    private void cerrar(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_cerrar
        // TODO add your handling code here:
        bandera=0;
        this.dispose();
    }//GEN-LAST:event_cerrar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
