/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.jefefuncional.vista;

/**
 *
 * @author Ricardo
 */
public class MenuJefeFuncional extends javax.swing.JFrame {

    /**
     * Creates new form MenuJefeFuncional
     */
    public MenuJefeFuncional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuSolicitud = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenuItem();
        menuRoles = new javax.swing.JMenuItem();
        menuVerSolicitudes = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        menuSolicitud.setMnemonic('o');
        menuSolicitud.setText("Crear Solicitud");
        menuSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSolicitudActionPerformed(evt);
            }
        });
        fileMenu.add(menuSolicitud);

        menuEmpleados.setMnemonic('s');
        menuEmpleados.setText("Ver Empleados");
        menuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadosActionPerformed(evt);
            }
        });
        fileMenu.add(menuEmpleados);

        menuRoles.setMnemonic('a');
        menuRoles.setText("Asignar Cargos");
        menuRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRolesActionPerformed(evt);
            }
        });
        fileMenu.add(menuRoles);

        menuVerSolicitudes.setText("Ver Solicitudes");
        menuVerSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerSolicitudesActionPerformed(evt);
            }
        });
        fileMenu.add(menuVerSolicitudes);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSolicitudActionPerformed
        desktopPane.removeAll();
        AperturaCasoJefeFuncional panel = new AperturaCasoJefeFuncional();
        this.setSize(panel.getWidth(), panel.getHeight() + 50);
        desktopPane.add(panel.getContentPane());
        desktopPane.updateUI();
    }//GEN-LAST:event_menuSolicitudActionPerformed

    private void menuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadosActionPerformed
        desktopPane.removeAll();
        VerEmpleados panel = new VerEmpleados();
        this.setSize(panel.getWidth(), panel.getHeight() + 50);
        desktopPane.add(panel.getContentPane());
        desktopPane.updateUI();
    }//GEN-LAST:event_menuEmpleadosActionPerformed

    private void menuRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRolesActionPerformed
        desktopPane.removeAll();
        AsignarRoles panel = new AsignarRoles();
        this.setSize(panel.getWidth(), panel.getHeight() + 50);
        desktopPane.add(panel.getContentPane());
        desktopPane.updateUI();
    }//GEN-LAST:event_menuRolesActionPerformed

    private void menuVerSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerSolicitudesActionPerformed
        desktopPane.removeAll();
        VerSolicitudes panel = new VerSolicitudes();
        this.setSize(panel.getWidth(), panel.getHeight() + 50);
        desktopPane.add(panel.getContentPane());
        desktopPane.updateUI();
    }//GEN-LAST:event_menuVerSolicitudesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJefeFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJefeFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJefeFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJefeFuncional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJefeFuncional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuEmpleados;
    private javax.swing.JMenuItem menuRoles;
    private javax.swing.JMenuItem menuSolicitud;
    private javax.swing.JMenuItem menuVerSolicitudes;
    // End of variables declaration//GEN-END:variables

}
