/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.jefefuncional.vista;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.jefefuncional.modelo.Empleado;
import sv.edu.udb.jefefuncional.modelo.JefeArea;
import sv.edu.udb.util.Conexion;

/**
 *
 * @author Raul
 */
public class VerEmpleados extends javax.swing.JFrame {
    Conexion con;
    int idJefe = 1;
    DefaultTableModel modelo;
    /**
     * Creates new form VerEmpleados
     */
    public VerEmpleados() {
        initComponents();
        Object[][] data = null;
        String[] columns = {"ID Empleado", "Nombres", "Apellidos", "DUI", "Fecha Nacimiento", "Usuario", "Cargo", "Area"};
        modelo = new DefaultTableModel(data, columns);
        this.tbEmpleados.setModel(modelo);
        actualizarTabla();
    }
    
    public void actualizarTabla() {
        List<Empleado> empleados = new ArrayList<>();
        try {
            JefeArea jefe = new JefeArea(idJefe);
            con = new Conexion();
            con.setRs("SELECT * FROM empleados WHERE idEmpleado != " + jefe.getIdEmpleado() + " AND areaEmpleado =" + jefe.getAreaEmpleado());
            ResultSet rs = con.getRs();
            while (rs.next()) {
                int idEmpleado = rs.getInt("idEmpleado");
                String nombresEmpleado = rs.getString("nombresEmpleado");
                String apellidosEmpleado = rs.getString("apellidosEmpleado");
                String duiEmpleado = rs.getString("duiEmpleado");
                String fechaNacimientoEmpleado = rs.getString("fechaNacimientoEmpleado");
                int usuarioEmpleado = rs.getInt("usuarioEmpleado");
                int cargoEmpleado = rs.getInt("cargoEmpleado");
                int areaEmpleado = rs.getInt("areaEmpleado");
                
                Empleado empleado = new Empleado();
                empleado.setIdEmpleado(idEmpleado);
                empleado.setNombresEmpleado(nombresEmpleado);
                empleado.setApellidosEmpleado(apellidosEmpleado);
                empleado.setDuiEmpleado(duiEmpleado);
                empleado.setFechaNacimientoEmpleado(fechaNacimientoEmpleado);
                empleado.setUsuarioEmpleado(usuarioEmpleado);
                empleado.setCargoEmpleado(cargoEmpleado);
                empleado.setAreaEmpleado(areaEmpleado);
                empleados.add(empleado);
            }
        } catch (SQLException ex) {

        } finally {
            try {
                con.cerrarConexion();
            } catch (SQLException ex) {

            }
        }
        
        modelo.setRowCount(0);
        for (Empleado emp : empleados) {
            Object[] row = {emp.getIdEmpleado(), emp.getNombresEmpleado(), emp.getApellidosEmpleado(), emp.getDuiEmpleado(),
                 emp.getFechaNacimientoEmpleado(), emp.getUsuarioEmpleado(), emp.getCargoEmpleado(), emp.getAreaEmpleado()
            };
            modelo.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Empleado", "Nombres", "Apellidos", "DUI", "Fecha Nacimiento", "Usuario", "Cargo", "Area"
            }
        ));
        jScrollPane1.setViewportView(tbEmpleados);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmpleados;
    // End of variables declaration//GEN-END:variables
}
