/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.admin.vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sv.edu.udb.admin.modelo.*;
import sv.edu.udb.util.Validaciones;

/**
 *
 * @author Ricardo
 */
public class PanelJefe extends javax.swing.JPanel {

    
    ModeloArea mArea;
    private String datoId;
    private String datoArea;
    private String idTipo;
    public String getDatoId() {
        return datoId;
    }
    public String getDatoArea() {
        return datoArea;
    }
    int inicio=0;
    /**
     * Creates new form PanelEmpleado
     * @param idTipo
     */
    public PanelJefe(String idTipo) {
        this.idTipo=idTipo;
        initComponents();
        mArea=new ModeloArea();
        llenarAreas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void llenarAreas(){
        cmbArea.removeAllItems();
        ArrayList<BeansArea> arregloArea=mArea.mostrarAreas(this.idTipo);
        arregloArea.forEach((objetoArea) -> {
            cmbArea.addItem(objetoArea);
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbArea = new javax.swing.JComboBox();
        btnAgregarArea = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(154, 146));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Area");

        cmbArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAreaItemStateChanged(evt);
            }
        });

        btnAgregarArea.setText("+");
        btnAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbArea, 0, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarArea)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarArea))
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAreaItemStateChanged
        // TODO add your handling code here:
        if(this.inicio==0){
            this.inicio++;
        }else{
            BeansArea datArea=(BeansArea)cmbArea.getSelectedItem();
            this.datoId=datArea.getId();
            this.datoArea=datArea.getArea();
        }
    }//GEN-LAST:event_cmbAreaItemStateChanged

    private void btnAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAreaActionPerformed
        // TODO add your handling code here:
        Validaciones valida=new Validaciones();
        String datoIngresa=JOptionPane.showInputDialog("Ingrese la el nombre de la nueva area: ");
            if(datoIngresa!=null){
                if(valida.datoVacio(datoIngresa)==true){
                    JOptionPane.showMessageDialog(null, "No ha ingresado ningun dato","Error",JOptionPane.ERROR_MESSAGE);

                }else if(valida.soloLetras(datoIngresa)==false){
                    JOptionPane.showMessageDialog(null, "Solo se puede ingresar letras","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    
                    if(mArea.ingresarArea(datoIngresa)){
                        JOptionPane.showMessageDialog(null, "Se ha ingresado el area correctamente","Guardado Exitoso",JOptionPane.INFORMATION_MESSAGE);
                        llenarAreas();
                    }else{
                        JOptionPane.showMessageDialog(null, "No se ha ingresado el area","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
    }//GEN-LAST:event_btnAgregarAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArea;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
