/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.admin.vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sv.edu.udb.admin.modelo.*;
import sv.edu.udb.util.Validaciones;

/**
 *
 * @author Ricardo
 */
public class PanelEmpleado extends javax.swing.JPanel {

    public String getDatoIdCargo() {
        return datoIdCargo;
    }

    public String getDatoCargo() {
        return datoCargo;
    }

    public String getDatoIdArea() {
        return datoIdArea;
    }

    
    ModeloArea mArea;
    ModeloCargo mCargo;
    private String datoIdArea;
    private String datoArea;
    private String datoIdCargo;
    private String datoCargo;
    private String idTipo;
    
    public String getDatoArea() {
        return datoArea;
    }
    int inicio=0, inicio2=0;
    /**
     * Creates new form PanelEmpleado
     */
    public PanelEmpleado(String idTipo) {
        this.idTipo=idTipo;
        initComponents();
        mArea=new ModeloArea();
        mCargo=new ModeloCargo();
        llenarAreas();
        llenarCargos();
    }
    public final void llenarAreas(){
        cmbArea.removeAllItems();
        ArrayList<BeansArea> arregloArea=mArea.mostrarAreas(this.idTipo);
        arregloArea.forEach((objetoArea) -> {
            cmbArea.addItem(objetoArea);
        });
        
    }
    public final void llenarCargos(){
        cmbCargo.removeAllItems();
        ArrayList<BeansCargo> arregloCargo=mCargo.mostrarCargos();
        arregloCargo.forEach((objetoCargo) -> {
            cmbCargo.addItem(objetoCargo);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbArea = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Areas");

        cmbArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAreaItemStateChanged(evt);
            }
        });

        jLabel2.setText("Cargo");

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCargoItemStateChanged(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Validaciones valida=new Validaciones();
        String datoIngresa=JOptionPane.showInputDialog("Ingrese la el nombre del nuevo Cargo: ");
            if(datoIngresa!=null){
                if(valida.datoVacio(datoIngresa)==true){
                    JOptionPane.showMessageDialog(null, "No ha ingresado ningun dato","Error",JOptionPane.ERROR_MESSAGE);

                }else if(valida.soloLetras(datoIngresa)==false){
                    JOptionPane.showMessageDialog(null, "Solo se puede ingresar letras","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    
                    if(mCargo.ingresarCargo(datoIngresa)){
                        JOptionPane.showMessageDialog(null, "El nuevo Cargo se ha ingresado correctamente","Guardado Exitoso",JOptionPane.INFORMATION_MESSAGE);
                        inicio2=0;
                        llenarCargos();
                    }else{
                        JOptionPane.showMessageDialog(null, "No se ha ingresado el Cargo","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAreaItemStateChanged
        // TODO add your handling code here:
         if(this.inicio==0){
            this.inicio++;
        }else{
            BeansArea datArea=(BeansArea)cmbArea.getSelectedItem();
            this.datoIdArea=datArea.getId();
            this.datoArea=datArea.getArea();
        }
    }//GEN-LAST:event_cmbAreaItemStateChanged

    private void cmbCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCargoItemStateChanged
        // TODO add your handling code here:
        if(this.inicio2==0){
            this.inicio2++;
        }else{
            BeansCargo datCargo=(BeansCargo)cmbCargo.getSelectedItem();
            this.datoIdCargo=datCargo.getId();
            this.datoCargo=datCargo.getCargo();
        }
    }//GEN-LAST:event_cmbCargoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JComboBox cmbCargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
